export const SEARCH_SCOPE_MODES = [
  "EXACT",
  "MULTI_FAMILY",
  "ALL_CLUBS",
  "ALL_EQUIPMENT",
] as const;

export type SearchScopeMode = (typeof SEARCH_SCOPE_MODES)[number];

export const SEARCH_SCOPE_MODE_CONTRACT = SEARCH_SCOPE_MODES.join("|");

export const DIALOGUE_ACTS = [
  "CATALOG_SEARCH", "PRODUCT_ADVICE", "ASK_PRODUCT_REASON", "ASK_PRODUCT_DETAILS",
  "ASK_PRODUCT_FIT", "ASK_COMPARISON", "ANSWER_PENDING_QUESTION", "ASK_WHAT_INFORMATION_NEEDED",
  "CHANGE_PRODUCT", "CHANGE_TOPIC", "FITTING_REQUEST", "STORE_QUESTION", "GENERAL_GOLF",
  "CONFIRMATION", "DECLINE", "CORRECTION", "GREETING", "THANKS", "GOODBYE", "SMALL_TALK",
  "HELP_REQUEST", "CLARIFICATION", "USER_FRUSTRATION", "GENERAL_QUESTION", "PRODUCT_DETAILS", "OTHER",
] as const;

export type DialogueAct = (typeof DIALOGUE_ACTS)[number];
export const DIALOGUE_ACT_CONTRACT = DIALOGUE_ACTS.join("|");

export const CURRENT_TURN_FACT_SOURCES = [
  "CURRENT_USER_EXPLICIT",
  "CURRENT_USER_PENDING_ANSWER",
  "CURRENT_USER_CORRECTION",
  "CONTEXT_INFERRED",
] as const;
export type CurrentTurnFactSource = (typeof CURRENT_TURN_FACT_SOURCES)[number];

export const FACT_MUTATION_INTENTS = ["NONE", "SET_NEW", "CORRECT_EXISTING"] as const;
export type FactMutationIntent = (typeof FACT_MUTATION_INTENTS)[number];
