-- Expanded additive seed for the shared golf equipment catalog.
-- Identity is model-level; shafts, lofts and prices remain inventory-unit data.
with seed(brand, category, model, normalized, priority, lifecycle, url) as (values
 ('TaylorMade','fairway-wood','Qi10','qi10',1,'CURRENT','https://www.taylormadegolf.com/'),
 ('TaylorMade','hybrid','Qi10 Rescue','qi10-rescue',1,'CURRENT','https://www.taylormadegolf.com/'),
 ('TaylorMade','iron','P790','p790',1,'CURRENT','https://www.taylormadegolf.com/'),
 ('TaylorMade','wedge','MG4','mg4',1,'CURRENT','https://www.taylormadegolf.com/'),
 ('TaylorMade','putter','Spider Tour','spider-tour',2,'RECENT','https://www.taylormadegolf.com/'),
 ('Callaway','fairway-wood','Paradym Ai Smoke','paradym-ai-smoke',1,'CURRENT','https://www.callawaygolf.com/'),
 ('Callaway','hybrid','Apex UW','apex-uw',2,'RECENT','https://www.callawaygolf.com/'),
 ('Callaway','iron','Apex Pro','apex-pro',2,'RECENT','https://www.callawaygolf.com/'),
 ('Callaway','wedge','Jaws Raw','jaws-raw',2,'RECENT','https://www.callawaygolf.com/'),
 ('Callaway','putter','Ai-ONE','ai-one',1,'CURRENT','https://www.callawaygolf.com/'),
 ('Titleist','fairway-wood','GT2','gt2',1,'CURRENT','https://www.titleist.com/'),
 ('Titleist','hybrid','GT2','gt2',1,'CURRENT','https://www.titleist.com/'),
 ('Titleist','iron','T200','t200',1,'CURRENT','https://www.titleist.com/'),
 ('Titleist','wedge','Vokey SM10','vokey-sm10',1,'CURRENT','https://www.titleist.com/'),
 ('Titleist','putter','Scotty Cameron Phantom','scotty-cameron-phantom',2,'RECENT','https://www.titleist.com/'),
 ('PING','fairway-wood','G440','g440',1,'CURRENT','https://ping.com/'),
 ('PING','hybrid','G440','g440',1,'CURRENT','https://ping.com/'),
 ('PING','iron','i530','i530',1,'CURRENT','https://ping.com/'),
 ('PING','wedge','ChipR','chipr',2,'RECENT','https://ping.com/'),
 ('PING','putter','PLD','pld',1,'CURRENT','https://ping.com/'),
 ('Cobra','fairway-wood','DS-ADAPT','ds-adapt',1,'CURRENT','https://www.cobragolf.com/'),
 ('Cobra','hybrid','KING Tec','king-tec',2,'RECENT','https://www.cobragolf.com/'),
 ('Cobra','iron','KING Tour','king-tour',2,'RECENT','https://www.cobragolf.com/'),
 ('Cobra','wedge','Snakebite','snakebite',2,'RECENT','https://www.cobragolf.com/'),
 ('Cobra','putter','King Vintage','king-vintage',3,'HISTORIC','https://www.cobragolf.com/'),
 ('Mizuno','fairway-wood','ST-X 230','st-x-230',2,'RECENT','https://mizunogolf.com/'),
 ('Mizuno','hybrid','ST-MAX 230','st-max-230',1,'CURRENT','https://mizunogolf.com/'),
 ('Mizuno','wedge','T24','t24',1,'CURRENT','https://mizunogolf.com/'),
 ('Mizuno','putter','M.Craft OMOI','m-craft-omoi',2,'RECENT','https://mizunogolf.com/'),
 ('Srixon','fairway-wood','ZX Mk II','zx-mk-ii',2,'RECENT','https://www.srixon.com/'),
 ('Srixon','hybrid','ZX Mk II','zx-mk-ii',2,'RECENT','https://www.srixon.com/'),
 ('Srixon','wedge','Cleveland RTX 6 ZipCore','cleveland-rtx-6-zipcore',1,'CURRENT','https://www.srixon.com/'),
 ('Srixon','putter','Z-Star','z-star',3,'HISTORIC','https://www.srixon.com/'),
 ('Cleveland Golf','putter','Frontline Elite','frontline-elite',2,'RECENT','https://www.clevelandgolf.com/'),
 ('PXG','fairway-wood','0311 Black Ops','0311-black-ops',1,'CURRENT','https://www.pxg.com/'),
 ('PXG','hybrid','0311 Black Ops','0311-black-ops',1,'CURRENT','https://www.pxg.com/'),
 ('PXG','wedge','0311 Sugar Daddy III','0311-sugar-daddy-iii',1,'CURRENT','https://www.pxg.com/'),
 ('Odyssey','wedge','X-Act','x-act',3,'HISTORIC','https://www.odysseygolf.com/'),
 ('Scotty Cameron','putter','Newport 2','newport-2',1,'CURRENT','https://www.scottycameron.com/'),
 ('Vokey','wedge','SM8','sm8',3,'HISTORIC','https://www.vokey.com/'),
 ('Honma','fairway-wood','TW767','tw767',1,'CURRENT','https://www.honmagolf.com/'),
 ('Honma','hybrid','TW757','tw757',2,'RECENT','https://www.honmagolf.com/'),
 ('Honma','wedge','TW-W','tw-w',2,'RECENT','https://www.honmagolf.com/'),
 ('XXIO','fairway-wood','13','13',1,'CURRENT','https://www.xxio.com/'),
 ('XXIO','hybrid','13','13',1,'CURRENT','https://www.xxio.com/'),
 ('XXIO','wedge','Crossover','crossover',3,'HISTORIC','https://www.xxio.com/'),
 ('Bridgestone Golf','fairway-wood','B3 MAX','b3-max',1,'CURRENT','https://www.bridgestonegolf.com/'),
 ('Bridgestone Golf','hybrid','B3 MAX','b3-max',1,'CURRENT','https://www.bridgestonegolf.com/'),
 ('Tour Edge','hybrid','Exotics C725','exotics-c725',1,'CURRENT','https://www.touredge.com/'),
 ('Tour Edge','iron','Exotics E725','exotics-e725',2,'RECENT','https://www.touredge.com/'),
 ('Miura','wedge','MG-Hybrid','mg-hybrid',3,'HISTORIC','https://miuragolf.com/'),
 ('PRGR','fairway-wood','RS X','rs-x',1,'CURRENT','https://www.prgr-golf.com/'),
 ('PRGR','hybrid','Q','q',2,'RECENT','https://www.prgr-golf.com/'),
 ('Yonex','driver','EZONE GT','ezone-gt',2,'RECENT','https://www.yonex.com/'),
 ('Yonex','fairway-wood','EZONE GT','ezone-gt',2,'RECENT','https://www.yonex.com/'),
 ('Fourteen Golf','iron','TC-7','tc-7',3,'HISTORIC','https://www.fourteengolf.com/'),
 ('Epon','wedge','Tour Wedge','tour-wedge',3,'HISTORIC','https://epongolf.com/'),
 ('Proto Concept','wedge','C05','c05',2,'RECENT','https://protoconcept.com/'),
 ('MacGregor Golf','driver','MACTEC NVG2','mactec-nvg2',3,'HISTORIC','https://www.macgregorgolf.com/'),
 ('Ben Hogan Golf','wedge','Equalizer II','equalizer-ii',3,'HISTORIC','https://benhogangolf.com/'),
 ('Adams Golf','fairway-wood','Tight Lies','tight-lies',3,'HISTORIC','https://www.adamsgolf.com/'),
 ('Adams Golf','hybrid','Idea','idea',3,'HISTORIC','https://www.adamsgolf.com/'),
 ('Takomo Golf','iron','101T','101t',1,'CURRENT','https://takomogolf.com/'),
 ('Sub 70','iron','699','699',1,'CURRENT','https://sub70golf.com/'),
 ('Haywood Golf','iron','Signature','signature',1,'CURRENT','https://haywoodgolf.com/'),
 ('LA Golf','iron','L Series','l-series',1,'CURRENT','https://lagolf.com/')
)
insert into public.catalog_product_models (brand_id, category_id, model_name, normalized_model_name, lifecycle_status, reference_priority, reference_status, reference_source, reference_url, last_verified_at)
select b.id, c.id, s.model, s.normalized, s.lifecycle, s.priority, 'VERIFIED', 'OFFICIAL_MANUFACTURER', s.url, now()
from seed s join public.brands b on b.slug = lower(replace(s.brand,' ', '-'))
join public.categories c on c.slug = s.category
on conflict (brand_id, category_id, normalized_model_name) do update set
 lifecycle_status=excluded.lifecycle_status, reference_priority=excluded.reference_priority,
 reference_status='VERIFIED', reference_source=excluded.reference_source,
 reference_url=excluded.reference_url, last_verified_at=excluded.last_verified_at, status='active';
